<robot name="mycar" xmlns:xacro="http://wiki.ros.org/xacro">
    <!-- 1.属性定义 -->
    <xacro:property name="PI" value="3.1415927" />
    <xacro:property name="radius" value="0.03" />
    <!-- 2.属性调用 -->
    <myUsePorpertyxxx name="${PI}" />
    <myUsePorpertyxxx name="${radius}" />
    <!-- 3.算术运算 -->
    <myUsePorpertyxxx result="${PI / 2}" />
    <myUsePorpertyxxx result="${radius * 2}" />
</robot>
